In [0]:
import numpy as np

L = [1, 2, 3]
A = np.array([1, 2, 3])

In [3]:
for e in L:
    print(e)

1
2
3


In [4]:
for e in A:
    print(e)

1
2
3


In [0]:
L.append(4)

In [6]:
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: ignored

In [0]:
L = L + [5]

In [10]:
L

[1, 2, 3, 4, 5]

In [11]:
A = A + [4, 5]

ValueError: ignored

In [0]:
L2 = []
for e in L:
    L2.append(e+e)

In [15]:
L2

[2, 4, 6, 8, 10]

In [16]:
A + A

array([2, 4, 6])

In [17]:
2*A

array([2, 4, 6])

In [18]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
L**2

TypeError: ignored

In [20]:
L2 = []
for e in L:
    L2.append(e*e)
L2

[1, 4, 9, 16, 25]

In [21]:
A**2

array([1, 4, 9])

In [22]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [23]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [0]:
a = np.array([1, 2])
b = np.array([2, 1])

In [0]:
dot = 0

for e, f in zip(a, b):
    dot += a*b

In [27]:
dot

array([4, 4])

In [28]:
a*b 

array([2, 2])

In [29]:
np.sum(a*b)

4

In [30]:
(a*b).sum()

4

In [31]:
np.dot(a, b)

4

In [32]:
a.dot(b)

4

In [33]:
b.dot(a)

4

In [0]:
amag = np.sqrt((a*a).sum())

In [35]:
amag

2.23606797749979

In [36]:
amag = np.linalg.norm(a)
amag

2.23606797749979

In [37]:
cosangle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.7999999999999998

In [0]:
angle = np.arccos(cosangle)

In [39]:
angle

0.6435011087932847