In [0]:
import numpy as np
A = np.array([[1,2], [3,4]])

In [4]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [6]:
A.dot(Ainv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [7]:
np.linalg.det(A)

-2.0000000000000004

In [8]:
np.diag(A)

array([1, 4])

In [9]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [10]:
a = np.array([1,2])
b = np.array([3,4])
np.outer(a, b)

array([[3, 4],
       [6, 8]])

In [13]:
np.inner(a, b)

11

In [14]:
np.dot(a, b)

11

In [15]:
np.diag(A).sum()

5

In [16]:
np.trace(A)

5

In [0]:
X = np.random.randn(100,3)

In [0]:
cov = np.cov(X)

In [20]:
cov.shape

(100, 100)

In [0]:
cov = np.cov(A.T)

In [22]:
cov

array([[2., 2.],
       [2., 2.]])

In [23]:
np.linalg.eigh(cov)

(array([0., 4.]), array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [25]:
np.linalg.eig(cov)

(array([4.0000000e+00, 4.4408921e-16]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
b

array([3, 4])

In [0]:
b = np.array([1,2])

In [29]:
b

array([1, 2])

In [31]:
x = np.linalg.inv(A).dot(b)
x

array([0. , 0.5])

In [0]:
x = np.linalg.solve(A, b)

In [33]:
x

array([0. , 0.5])