In [0]:
import numpy as np

In [0]:
M = np.array([[1, 2], [3, 4]])

In [0]:
L = [[1, 2], [3, 4]]

In [11]:
L[0]

[1, 2]

In [12]:
L[0][0]

1

In [13]:
M[0][0]

1

In [14]:
M[0,0]

1

In [15]:
M

array([[1, 2],
       [3, 4]])

In [0]:
M2 = np.matrix([[1, 2], [3, 4]])

In [17]:
M2

matrix([[1, 2],
        [3, 4]])

In [0]:
A = np.array(M2)

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
A.T

array([[1, 3],
       [2, 4]])

In [21]:
# Creating an array of zeros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
O = np.ones((10,10))

In [24]:
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
R = np.random.random((10,10))
R

array([[1.93099073e-01, 6.17056293e-01, 3.39559052e-01, 4.14097679e-01,
        1.44252855e-01, 1.90901793e-01, 5.07499553e-01, 5.82608057e-01,
        8.55552933e-01, 2.02699259e-01],
       [2.45849902e-01, 8.79310888e-01, 7.07410646e-01, 6.06468414e-01,
        9.26821873e-01, 6.11977778e-01, 8.70780546e-01, 6.98362238e-01,
        9.94074172e-01, 5.01909298e-01],
       [3.11490715e-01, 1.49762550e-01, 4.22680188e-01, 4.39399600e-01,
        2.14044083e-01, 2.69309711e-01, 7.24853897e-01, 2.37335654e-01,
        8.02106892e-01, 8.82663762e-01],
       [7.19922556e-01, 6.51130020e-01, 7.03521791e-01, 4.44224444e-01,
        8.01065553e-01, 7.87208702e-01, 1.84498411e-01, 1.19741516e-01,
        2.40099979e-01, 2.74912169e-03],
       [2.75545248e-01, 4.12750911e-02, 6.39537058e-01, 6.84779612e-01,
        3.56278879e-01, 9.32020994e-01, 8.03090183e-01, 2.24633878e-01,
        5.62504805e-01, 4.41548814e-01],
       [6.68017907e-02, 4.75733320e-04, 8.55556019e-01, 6.80049111e-01,
   

In [27]:
G = np.random.randn((10,10))

TypeError: ignored

In [0]:
G = np.random.randn(10,10)

In [29]:
G

array([[ 1.2577941 , -0.58546589,  0.84968042, -0.37334882, -0.23096835,
         0.29632743, -1.68945258,  2.44259952,  0.98751432,  0.08894844],
       [-0.61662597,  1.52037593,  0.9486956 , -0.11178286,  0.79669388,
        -1.88915544, -0.0513209 ,  0.55824709, -1.23465768,  0.02184767],
       [-0.59941715, -0.08414716,  1.99547542,  0.0194855 ,  0.10082827,
         0.0598301 ,  0.82783145,  1.51652546,  0.00328887,  1.43486974],
       [-1.39668796,  0.51373968, -0.89830643, -0.344804  ,  1.38983036,
        -2.35032606,  0.92929125, -0.17220326, -1.17820892, -1.10891391],
       [-0.84542757, -0.0731635 ,  0.70913372,  0.20013697, -0.45635351,
         0.86902285, -1.56811074, -0.22322415, -0.0819068 ,  0.78951157],
       [-1.36231669, -0.00755452,  1.96224487,  1.05931922,  1.29972546,
         0.62538107,  0.92237762,  1.25349499, -0.09052201,  0.83672057],
       [-0.33024061,  0.65982473, -0.91412441,  1.19265359, -0.24550639,
        -1.11457672, -0.89936907,  1.25377308

In [30]:
G.mean()

0.12935490030000701

In [31]:
G.var()

0.9475721443124974